/**
 * Generates codebook.md and analysis/generated_scales.R from the item bank,
 * the awareness/comparative modules, and the column contract.
 *
 * Run: npm run gen:codebook
 *
 * All three source files (items.ts, awareness.ts, comparative.ts) feed both
 * outputs, so the codebook and the R analysis cannot describe a different
 * instrument than the one actually administered. Do not hand-edit either
 * output.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  RATED_ITEMS, DOWNSTREAM_CHOICE_OPTIONS, DOWNSTREAM_ORDINAL, DOWNSTREAM_CHOICE_STEM,
  BLOCK_OPEN_ENDED_STEM, SCALE_LABELS,
} from '../src/data/items';
import { AWARENESS_STEM, AWARENESS_STATEMENTS, AWARENESS_DONT_REMEMBER } from '../src/data/awareness';
import {
  C1_STEM, C2_STEM, C3_STEM, C4_STEM, C5_STEM, C6_STEM, C3_SCALE, C5_SCALE,
  recodeBrandChoice, recodeComparativeScale,
} from '../src/data/comparative';
import { COLUMNS, BLOCK_PREFIXES, POPUP_PREFIXES } from '../src/data/columns';
import { ARM_TARGETS, ARMS, DECLINE_COPY } from '../src/data/conditions';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');

const esc = (s: string) => s.replace(/\|/g, '\\|');

// ── codebook.md ────────────────────────────────────────────────────────────

const groups = [...new Set(COLUMNS.map((c) => c.group))];

// Truth table for the comparative recode functions, generated by actually
// CALLING them — so if the functions ever change, this table changes with
// them rather than silently going stale.
const BRAND_TRUTH = (
  ['aurevella', 'veloure', 'both', 'neither', 'compare_further', 'dont_remember'] as const
).map((raw) => ({
  raw,
  whenExpIsAurevella: recodeBrandChoice(raw, 'aurevella'),
}));

const SCALE_TRUTH = [1, 4, 7].map((raw) => ({
  raw,
  brand1IsNeutral: recodeComparativeScale(raw, true),
  brand1IsExp: recodeComparativeScale(raw, false),
}));

const md = `# Codebook — Confirmshaming Storefront Study (Instrument v2)

> **GENERATED FILE — do not edit by hand.**
> Source: \`src/data/items.ts\`, \`src/data/awareness.ts\`, \`src/data/comparative.ts\` and
> \`src/data/columns.ts\`. Regenerate with \`npm run gen:codebook\`.
> Because the CSV, this codebook and \`analysis/generated_scales.R\` are all produced from those
> files, they cannot describe an instrument different from the one actually administered.

One row per participant. **${COLUMNS.length} columns.**

This is **Instrument v2** (see \`Instrument_v2.md\`, which replaces PRD §4 and §5). It trades the
v1 multi-item, multi-factor battery (72 rated items, Cronbach's alpha, five factors) for five
single-item measures per brand (change_spec_v4_final.md Part 4 moved the stems from pop-up level to
brand level once each brand started showing two pop-ups), to protect completion on phones. **What's kept:**
perceived manipulation, irritation (the mediator), brand trust, a downstream behavioural choice,
awareness, and the within-person difference score. **What's given up:** Cronbach's alpha, the
credibility axis, brand attributions, and the guilt/anger/amusement factor structure. State this
trade-off in the limitations slide — "single-item measures were used to protect completion rates
at N = 40" is a defensible sentence.

---

## 1. The rated items (B1–B4), in fixed presentation order

No randomisation within the block: with only four items, "feelings before intent" is a per-item
ordering constraint, and shuffling risks putting the manipulation item before irritation by chance.

| # | Item | Wording | Scale | Note |
| --- | --- | --- | --- | --- |
${RATED_ITEMS.map(
  (item, i) =>
    `| ${i + 1} | \`${item.id}\` | ${esc(item.text)} | ${SCALE_LABELS[item.scale]} | ${esc(item.note)} |`,
).join('\n')}

**No item is reverse-coded.** None of the four items are worded in the opposite direction to their
construct, so \`analysis_starter.R\` does no reverse-coding pass — a change from v1, where the IMI
battery needed it.

**\`b4_trust\` is deliberately level-framed** ("I would trust this brand"), not change-framed. The
within-person difference score (\`diff_b4_trust\` = exp − neutral) is what measures the trust
penalty; a change-framed item would nest with that difference and become uninterpretable. A level
item also lets trust go **up** in the autonomy arm, which H4 predicts — a change-framed item cannot
detect that.

## 2. Downstream choice (B5)

> ${esc(DOWNSTREAM_CHOICE_STEM)}

Stored raw (\`b5_raw\`) **and** as a derived ordinal (\`b5_ord\`), so it can be differenced like the
rated items:

| Option | Ordinal |
| --- | --- |
${DOWNSTREAM_CHOICE_OPTIONS.map((o) => `| ${esc(o.label)} (\`${o.value}\`) | ${DOWNSTREAM_ORDINAL[o.value] ?? 'NA'} |`).join('\n')}

With 13 per arm the raw five-way cross-tab will have cells of two or three people. Report
\`diff_b5\` (the ordinal difference score) as the headline, the raw cross-tab as colour.

## 3. Open-ended (B6)

> ${esc(BLOCK_OPEN_ENDED_STEM)}

Optional, skippable immediately — no minimum length, no forced wait (a deliberate departure from
v1's OpenEnded screen, which had both; v2 measures this per block instead of once at the end).

## 4. Questionnaire order (forced, no back navigation)

1. **Block A** — B1–B6, for the first pop-up shown
2. **Block B** — B1–B6, identical, for the second pop-up shown
3. **Awareness** — asked once per brand, retrospectively, after BOTH blocks
4. **Comparative** — C1–C6
5. **Covariates**, then **demographics**

Feelings (\`b1_guilt\`, \`b2_irritation\`) are always measured before the item that names pressure or
intent (\`b3_manipulation\`), inside each block — the Campbell (1995) / Cotte et al. (2005) demand-
effect constraint carried over from v1.

## 5. Awareness check (asked twice, after both blocks)

> ${esc(AWARENESS_STEM.replace('{BRAND}', '<brand name>'))}

Never asked immediately after a pop-up: an immediate check on pop-up A would prime the participant
for pop-up B and destroy the "Ignore" classification for the second brand.

**The stem and options never quote a literal decline wording.** The neutral condition's button
literally reads "No thanks" — quoting any condition verbatim would cue the answer for whoever saw
that exact wording. Options are descriptions of what the wording implied:

| Condition | Statement offered |
| --- | --- |
${Object.entries(AWARENESS_STATEMENTS).map(([k, v]) => `| \`${k}\` | ${esc(v)} |`).join('\n')}
| \`dont_remember\` | ${esc(AWARENESS_DONT_REMEMBER)} |

Options are shuffled per participant per question (first four only — "don't remember" is always
last). Stored **by presentation position** (\`aware_brand1_raw\`, \`aware_brand2_raw\`, meaning
"first store visited" / "second store visited" — NOT condition), then correctness is recoded **by
condition** (\`aware_neutral_correct\`, \`aware_exp_correct\`) since position and condition are
independently counterbalanced. "Don't remember" counts as incorrect.

## 6. Comparative block (screen 11)

> **This block is corroborating evidence, not primary evidence.** Asking participants to compare
> the two pop-ups directly makes the manipulation salient and invites them to construct a
> difference they may not have felt. Primary evidence is the behavioural logs and the B1–B5
> difference scores, both collected before this block exists. **If this block contradicts the
> behavioural data, believe the behavioural data.**

| # | Stem | Type |
| --- | --- | --- |
| C1 | ${esc(C1_STEM)} | Brand 1 / Brand 2 / both / neither / don't remember |
| C2 | ${esc(C2_STEM)} | Brand 1 / Brand 2 / both / neither |
| C3 | ${esc(C3_STEM)} | 1 = ${C3_SCALE.low} … 4 = ${C3_SCALE.mid} … 7 = ${C3_SCALE.high} |
| C4 | ${esc(C4_STEM)} | Brand 1 / Brand 2 / compare further / neither |
| C5 | ${esc(C5_STEM)} | 1 = ${C5_SCALE.low} … 4 = ${C5_SCALE.mid} … 7 = ${C5_SCALE.high} |
| C6 | ${esc(C6_STEM)} | Open-ended, optional |

### 6.1 Brand 1 / Brand 2 mean PRESENTATION POSITION, not condition

Roughly half of participants saw the neutral pop-up on the first brand and half on the second.
Every raw comparative answer is stored as an actual brand id, and **must be recoded relative to
\`brand_experimental\`, never interpreted as "Brand 1 vs Brand 2" directly.**

### 6.2 Recoding — generated by calling the functions, not hand-typed

\`recodeBrandChoice(raw, expBrand)\` — feeds C1, C2 and C4 (\`src/data/comparative.ts\`):

| Raw answer | Recodes to (when Aurevella is \`brand_experimental\`) |
| --- | --- |
${BRAND_TRUTH.map((r) => `| \`${r.raw}\` | ${r.whenExpIsAurevella === null ? 'NA' : r.whenExpIsAurevella} |`).join('\n')}

Note that \`both\` / \`neither\` / \`compare_further\` all recode to **0**, not NA — only C1's
"don't remember" recodes to NA. This is the instrument's literal rule, not an oversight.

\`recodeComparativeScale(raw, expBrandIsPositionTwo)\` — feeds C3 and C5:

| Raw | If Brand 1 is the NEUTRAL brand (reverse: \`8 − raw\`) | If Brand 1 is the EXPERIMENTAL brand (unchanged) |
| --- | --- | --- |
${SCALE_TRUTH.map((r) => `| ${r.raw} | ${r.brand1IsNeutral} | ${r.brand1IsExp} |`).join('\n')}

\`expBrandIsPositionTwo\` is simply \`order === 'neutral_first'\`: neutral-first means position 1 is
the neutral brand, so the experimental brand is Brand 2 and the raw scale must reverse to keep
"high = more, relative to the experimental brand" true regardless of presentation order.

## 7. Conditions

| Condition | Decline-button wording |
| --- | --- |
${Object.entries(DECLINE_COPY).map(([k, v]) => `| \`${k}\` | "${v}" |`).join('\n')}

**This wording is the only difference between arms.** Headline, offer, accept label, close
"X", tap-target size, contrast, animation and timing are identical, enforced by
\`src/screens/Popup.identical.test.tsx\`.

## 8. Two pop-ups per brand (v4)

Each brand now shows **two** pop-ups (change_spec_v4_final.md Part 2), not one: **p1** fires on
checkout intent (add-to-bag), exactly as the single pop-up used to; **p2** fires on a new
order-confirmation screen that follows p1. Both of a brand's pop-ups carry that brand's decline
wording — **never mixed within a brand** — so every per-pop-up column below is duplicated as
\`_p1_\` / \`_p2_\`, while fields that describe the block rather than either pop-up (\`condition\`,
\`brand\`, \`block_position\`, \`decline_label\`, \`product_viewed\`, \`time_on_store_ms\`) stay singular.

Both pop-ups' copy references collecting contact details (an email for p1's discount, a follow for
p2's), but **neither actually collects anything**: no text input is ever rendered, nothing typed is
ever stored, and accepting simply shows a confirmation message on the following screen before
moving on. \`neutral_accepts\` / \`exp_accepts\` / \`diff_accepts\` count how many of a block's two
pop-ups were accepted (0–2), as a second, purely behavioural outcome alongside the rated-item
difference scores.

## 9. Assignment mechanism

**Arm comes from the recruiting link, not from the app** (change_spec_v4_final.md, v4). Each
participant's link carries an opaque \`?g=\` code; decoding it (\`src/data/groupCodes.ts\`) gives the
arm directly — v4 drops the recruiter dimension entirely, so there is no \`recruiter_id\` column.
The exact code-to-arm table is deliberately **not** reproduced here — see \`README.md\` (kept by the
study team, never shared with participants) and the source file itself. A missing or unrecognised
code never falls back to a fixed arm: the client draws one uniformly at random and records
\`assignment_source = "random"\`, so that count is visible and reportable as a limitation rather than
silently stacking participants into one condition.

\`order\` and \`pairing\` are nuisance factors, not the allocation being controlled, so they are drawn
per participant with \`Math.random()\` rather than from a pre-generated sequence — exact balance
across cells isn't required, only that they vary.

> **Superseded, twice over.** Before change_spec_group_codes.md (v3), a pre-generated, seeded
> 52-slot sequence was served one slot at a time by the Apps Script's \`assign\` endpoint, which
> guaranteed an exact 13/13/14 split — that endpoint still exists in \`apps-script/Code.gs\` (the
> script was left unmodified) but nothing calls it any more; do not treat \`?action=assign\` as live,
> it is vestigial. v3 then replaced that sequence with a \`?g=\` code carrying BOTH an arm and a
> recruiter (four recruiters × three arms, twelve codes) and a \`recruiter_id\` column. v4
> (change_spec_v4_final.md) drops the recruiter dimension entirely — three links, one per arm, no
> recruiter attribution, no \`recruiter_id\` column.

## 10. Response-type coding (derived, never asked)

Computed once PER POP-UP. Recomputed in R from \`choice\`, \`latency_ms\` and awareness correctness,
so the threshold can be re-tuned:

| Behaviour | Code | Interpretation |
| --- | --- | --- |
| Accepts the offer | \`comply\` | Short-term effectiveness |
| Taps the loaded decline button | \`resist\` | Deliberate confrontation; reactance |
| Closes via "X" / backdrop, or times out | \`avoid\` | Shame avoidance rather than offer rejection |
| Dismissal < 1500 ms **and** fails the awareness check | \`ignore\` | Tactic passed unnoticed |

## 11. Exclusion rules

Apply before analysis:

1. \`is_debug == TRUE\` — pilot and debug runs. Always exclude.
2. \`status != "complete"\` — dropouts. Keep them to report the abandonment rate, exclude from
   outcome models.
3. \`*_p1_popup_render_gap_ms > 2000\` or \`*_p2_popup_render_gap_ms > 2000\` — a pop-up that took
   over 2 s to paint makes THAT pop-up's latency uninterpretable. Apply per pop-up, not per block.
4. \`resumed_after_reload == TRUE\` **with null timing** — the participant reloaded mid-measurement.
   Self-report is still usable; the affected pop-up's behavioural columns are null by design.
5. \`assignment_source == "random"\` — the participant's link had a missing or unrecognised group
   code, so the client picked an arm uniformly at random. Not part of the intended 15/15/15
   allocation. Report the count as a limitation rather than dropping silently.
6. \`*_p1_abandoned == TRUE\` or \`*_p2_abandoned == TRUE\` on an otherwise-\`complete\` row should not
   happen (a complete row means every pop-up resolved) — treat it as a bug if seen, not as data to
   exclude.

## 12. Deviations from the PRD / v1 instrument

Each is deliberate; each is here so the write-up can state it rather than discover it.

| PRD / v1 says | Implemented as | Why |
| --- | --- | --- |
| Arm assigned by the app (pre-generated sequence via the Apps Script) | Arm decoded from the recruiting link's \`?g=\` group code; \`order\`/\`pairing\` drawn per participant | change_spec_group_codes.md (v3), refined by change_spec_v4_final.md (v4): a clean split needs each arm drawing from an independent link, which only link-based control can guarantee. \`slot\` and (as of v4) \`recruiter_id\` are removed from the schema entirely. |
| One pop-up per brand | Two pop-ups per brand (checkout + order confirmation), same decline wording within a brand | change_spec_v4_final.md Part 2: the original 15%-off-at-no-cost pop-up put acceptance at ceiling, leaving no room for the manipulation to show a behavioural difference. Both new pop-ups attach a cost to accepting. |
| 72 rated items, 9 multi-item scales | 8 rated items (B1–B4 × 2 blocks) + downstream choice + comparative block | Instrument v2 (\`Instrument_v2.md\`): reliability traded for completion at N = 40 on phones. |
| Cronbach's alpha per scale | None — every rated item is single-item | No multi-item scale exists in v2 to compute alpha over. |
| Recognition check, immediate options | Awareness check, descriptive (non-literal) options, still asked after both blocks | Both v1 and v2 ask retrospectively; v2's options describe the wording's implication rather than quoting it, so no option can cue the participant who saw that exact condition. |
| \`mode: 'no-cors'\` POST | CORS-simple \`text/plain\` POST | An opaque response resolves successfully even on a 500, making retry-and-rescue logic unreachable. Unaffected by the v1→v2 instrument change. |
| \`*_abandoned\` per block | Session-level \`abandoned\` + \`abandoned_at_step\`, PLUS a per-pop-up \`*_p1_abandoned\`/\`*_p2_abandoned\` (v4) | A participant abandons a session, not a pop-up — but with two pop-ups per block now, which specific pop-up was never reached is itself useful information a single session-level flag can't give. |
| \`cancelled_taps\` includes \`pointercancel\` | Split into \`cancelled_taps\` and \`pointer_cancels\` | On Android \`pointercancel\` fires on every scroll. |
| Continuation "6 s or until action" | Live from 0 s, auto-advance at 8 s, censoring flagged | Ambiguous between a floor and a ceiling. |
| \`abandon\` response code, no threshold | \`timeout\` at 45 s | Without a timeout a frozen participant loses the entire row. |
| ~6 minutes (v1: 8–10 due to item load) | Consent states ${'`'}about 6 minutes${'`'} again | v2's much shorter instrument (~23 items total vs ~80) makes the original PRD estimate realistic. Confirm against pilot times. |

## 13. All columns

${groups
  .map((group) => {
    const cols = COLUMNS.filter((c) => c.group === group);
    return `### ${group}

| Column | Type | Scale / values | Description |
| --- | --- | --- | --- |
${cols
  .map(
    (c) =>
      `| \`${c.name}\` | ${c.type} | ${esc(
        c.scale ?? (c.values ? c.values.map((v) => `\`${v}\``).join(', ') : '—'),
      )} | ${esc(c.description)}${c.note ? ` *${esc(c.note)}*` : ''} |`,
  )
  .join('\n')}`;
  })
  .join('\n\n')}
`;

writeFileSync(resolve(ROOT, 'codebook.md'), md);

// ── analysis/generated_scales.R ────────────────────────────────────────────

const ratedIdList = RATED_ITEMS.map((i) => `"${i.id}"`).join(', ');
const ratedLabelList = RATED_ITEMS.map((i) => `  ${i.id} = "${i.text.replace(/"/g, '\\"')}"`).join(',\n');
const downstreamOrdinalR = Object.entries(DOWNSTREAM_ORDINAL)
  .map(([k, v]) => `  ${k} = ${v === null ? 'NA' : v}`)
  .join(',\n');

const r = `# GENERATED FILE — do not edit by hand.
# Source: src/data/items.ts via scripts/gen-codebook.ts. Regenerate: npm run gen:codebook
#
# Sourced by analysis_starter.R. Keeping these definitions generated is what
# guarantees the column list and the ordinal mapping used in analysis matches
# the instrument that was actually administered.

BLOCK_PREFIXES <- c(${BLOCK_PREFIXES.map((p) => `"${p}"`).join(', ')})

# change_spec_v4_final.md Part 2: two pop-ups per brand block, p1 (checkout)
# and p2 (order confirmation). Behavioural columns are \${BLOCK_PREFIX}_\${POPUP_PREFIX}_*.
POPUP_PREFIXES <- c(${POPUP_PREFIXES.map((p) => `"${p}"`).join(', ')})

# Instrument v2: single-item measures. No reverse-coding — none of the four
# rated items are worded opposite to their construct.
RATED_ITEMS <- c(${ratedIdList})

RATED_ITEM_LABELS <- c(
${ratedLabelList}
)

# B5 downstream choice: ordinal mapping (not_sure = NA).
DOWNSTREAM_ORDINAL <- c(
${downstreamOrdinalR}
)

ARMS <- c(${ARMS.map((a) => `"${a}"`).join(', ')})
ARM_TARGETS <- c(${ARMS.map((a) => `${a} = ${ARM_TARGETS[a]}`).join(', ')})

# PRD §11: a pop-up that took longer than this to paint makes that block's
# latency uninterpretable.
RENDER_GAP_EXCLUSION_MS <- 2000
# PRD §5.2: fast dismissal threshold for the provisional "Ignore" code.
IGNORE_LATENCY_MS <- 1500
`;

mkdirSync(resolve(ROOT, 'analysis'), { recursive: true });
writeFileSync(resolve(ROOT, 'analysis/generated_scales.R'), r);

console.log(`Wrote codebook.md — ${COLUMNS.length} columns, ${RATED_ITEMS.length} rated items (v2, no reverse-coding)`);
console.log('Wrote analysis/generated_scales.R');
